# Generated by Django 4.0.1 on 2022-08-31 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='last_session_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 31, 16, 5, 35, 814096), verbose_name='last session updated'),
        ),
    ]
